### ISSUE TITLE
MP4 + SRT frame extraction and tagging

### ISSUE THREAD

**Issue by michaelthoreau** [pierotofy/drone_dataset_dji_video#1]
This looks like a dataset to test out frame extraction. Here's our basic workflow. If anyone wants to iterate on this and open source it, please do!

current deficiencies: We use tags from a gopro for most of a the exif... 

https://colab.research.google.com/drive/14SVPX3rnPdSTxQg3xnHXwp-mJgAX35sX?usp=sharing

**Comment by pierotofy** [comment]
Thanks @michaelthoreau :+1: this was actually to add a test for ODM, which now has built-in support for extracting video frames (works similarly to your code in some parts). https://github.com/OpenDroneMap/ODM/pull/1567

We'd love to get improvements to ODM in this area if you've been working on it also.

**Comment by michaelthoreau** [comment]
I feel like i knew that was coming, we’ll switch to using the inbuilt version then!

We’ll look at contributing where we can!

Currently wondering about a fast approximate coverage estimator based on the trajectory from the SRT and a simple projection based on altitude.   Not having to do a full sfm would be helpful i think.
